[package]
name = "abyss"
description = "EclipseOS Wayland compositor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "abyss"
path = "src/main.rs"

[dependencies]
smithay = { workspace = true, features = [
  "wayland_frontend",
  "desktop",
  "renderer_gl",
  "xwayland",
] }
calloop.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-journald.workspace = true
anyhow.workspace = true
thiserror.workspace = true
xkbcommon.workspace = true
libc = "0.2"
kdl.workspace = true
serde_json.workspace = true

[features]
default = ["winit", "drm"]
winit = ["smithay/backend_winit"]
# Production backend: KMS via libseat + udev + libinput, GLES on GBM/EGL.
drm = [
  "smithay/backend_drm",
  "smithay/backend_gbm",
  "smithay/backend_egl",
  "smithay/backend_libinput",
  "smithay/backend_session",
  "smithay/backend_session_libseat",
  "smithay/backend_udev",
  "smithay/use_system_lib",
]
