// SPDX-License-Identifier: AGPL-3.0-only
//! `docs/CONFIG.md` is generated from the schema, not written by hand.
//!
//! F-07 §7 makes `docs/` source of truth once code starts, and a
//! hand-maintained key reference is a promise to let the two drift. So the
//! reference is a function of `config::schema::TABLE`, and this test fails if
//! the checked-in file is not what that function produces. Regenerate with:
//!
//! ```text
//! UPDATE_CONFIG_DOC=1 cargo test -p abyss --test config_doc
//! ```

use std::fmt::Write as _;

use abyss::config::schema::{Collection, Dv, Key, Owner, Reload, Ty, COLLECTIONS, RULE_ACTIONS, TABLE};

fn ty(t: &Ty) -> String {
    match t {
        Ty::Bool => "bool".into(),
        Ty::Int { min, max } => format!("int {min}..{max}"),
        Ty::Float { min, max } => format!("float {min}..{max}"),
        Ty::Str => "string".into(),
        Ty::Enum(vs) => vs.join(" \\| "),
        Ty::Color => "colour `#rrggbb[aa]`".into(),
        Ty::StrList => "list of strings".into(),
    }
}

fn default(d: &Dv) -> String {
    match d {
        Dv::Null => "_unset_".into(),
        Dv::Bool(b) => format!("`#{b}`"),
        Dv::Int(i) => format!("`{i}`"),
        Dv::Float(f) => format!("`{f}`"),
        Dv::Str(s) => format!("`\"{s}\"`"),
        Dv::EmptyList => "_empty_".into(),
        Dv::Color([r, g, b, a]) => format!(
            "`#{:02x}{:02x}{:02x}{:02x}`",
            (r * 255.0) as u8,
            (g * 255.0) as u8,
            (b * 255.0) as u8,
            (a * 255.0) as u8
        ),
    }
}

fn file(o: Owner) -> &'static str {
    match o {
        Owner::Abyss => "abyss.kdl",
        Owner::Policy => "policy.kdl",
    }
}

fn section(out: &mut String, keys: &[&Key]) {
    out.push_str("| setting | type | default | reload | what it does |\n");
    out.push_str("| --- | --- | --- | --- | --- |\n");
    for k in keys {
        let reload = match k.reload {
            Reload::Live => "live",
            Reload::NeedsRestart => "restart",
        };
        let _ = writeln!(
            out,
            "| `{}` | {} | {} | {reload} | {} |",
            k.path,
            ty(&k.ty),
            default(&k.default),
            k.doc
        );
    }
    out.push('\n');
}

fn collections(out: &mut String, cs: &[&Collection]) {
    for c in cs {
        let _ = writeln!(out, "### `{}`\n\n{}\n", c.node, c.doc);
        if c.node == "windowrule" {
            out.push_str("| action | file |\n| --- | --- |\n");
            for (a, o) in RULE_ACTIONS {
                let _ = writeln!(out, "| `{a}` | `{}` |", file(*o));
            }
            out.push('\n');
        }
    }
}

fn generate() -> String {
    let mut out = String::new();
    out.push_str(
        "<!-- Generated by `cargo test -p abyss --test config_doc`. Do not edit by hand:\n     \
         the source is `crates/abyss/src/config/schema.rs`. -->\n\n\
         # Configuration reference\n\n\
         Every setting abyss understands, with the file it lives in (COMP-13 §1.3).\n\n\
         Configuration is two files, not one. `abyss.kdl` is everything cosmetic and\n\
         behavioural; `policy.kdl` is the security surface. The control socket — and so\n\
         every GUI, since a GUI writes only through the COMP-13 §1.4 API — can read both\n\
         and write only the first. Changing a policy setting is a decision a human makes\n\
         in a text editor, on purpose.\n\n\
         Both files are searched in `/etc/eclipse/` then `$XDG_CONFIG_HOME/eclipse/`, and\n\
         both are hot-reloaded. `eclipse-ctl config list` prints this same table with the\n\
         values you actually have; `eclipse-ctl config migrate` splits a legacy\n\
         single-file `abyss.kdl` into the two.\n\n\
         KDL v2: booleans are `#true` and `#false`, never bare `true`.\n\n",
    );

    for owner in [Owner::Abyss, Owner::Policy] {
        let _ = writeln!(out, "## `{}`\n", file(owner));
        if owner == Owner::Policy {
            out.push_str("Read-only over the socket. A GUI shows these; it cannot change them.\n\n");
        }
        let mut nodes: Vec<&str> = Vec::new();
        for k in TABLE.iter().filter(|k| k.owner == owner) {
            let node = k.path.split('.').next().unwrap_or(k.path);
            if !nodes.contains(&node) {
                nodes.push(node);
            }
        }
        for node in nodes {
            let keys: Vec<&Key> = TABLE
                .iter()
                .filter(|k| k.owner == owner && k.path.split('.').next() == Some(node))
                .collect();
            let _ = writeln!(out, "### `{node}`\n");
            section(&mut out, &keys);
        }
        let cs: Vec<&Collection> = COLLECTIONS.iter().filter(|c| c.owner == owner).collect();
        if !cs.is_empty() {
            collections(&mut out, &cs);
        }
    }
    out
}

#[test]
fn config_doc_is_current() {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../docs/CONFIG.md");
    let want = generate();
    if std::env::var_os("UPDATE_CONFIG_DOC").is_some() {
        std::fs::write(path, &want).expect("write docs/CONFIG.md");
        return;
    }
    let have = std::fs::read_to_string(path).unwrap_or_default();
    assert!(
        have == want,
        "docs/CONFIG.md is stale; regenerate with \
         `UPDATE_CONFIG_DOC=1 cargo test -p abyss --test config_doc`"
    );
}
