# SPDX-License-Identifier: AGPL-3.0-only
# Live medium only (D-03 §5): the greeter config with the installer's initial session.
[Service]
ExecStart=
ExecStart=/usr/bin/greetd --config /etc/eclipse/greetd-live.toml
